logging:
  path: /usr/local/jars/log/${spring.application.name}
spring:
  application:
    name: msa-weather-report-server

#    热部署静态文件
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates
    suffix: .html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connectionTimeout: 50000
        readTimeout: 50000
  hystrix:
    enabled: true
server:
  port: 8080
